---
params:
  city: sibiu
  country: romania
  city_roads_path: "data/gendered_street_names_fixed_geo/romania/city_roads_gender_fixed_geo-sibiu.rds"
output:
  html_document:
    self_contained: true
---

---
title: `r paste0("How many streets and squares are dedicated to women in ", stringr::str_to_title(params$city), "?")`
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library("genderedstreetnames")


```

These are all the streets of `r stringr::str_to_title(params$city)`.

```{r}
city_roads <- readRDS(file = params$city_roads_path)
```


```{r}
tmap::tmap_mode(mode = "plot")
city_boundary <- Get_city_boundaries(city = params$city, country = params$country, cache = TRUE)

all_streets_city_map <- tmap::tm_shape(city_boundary) + 
  tmap::tm_polygons() +
  tmap::tm_shape(city_roads) +
  tmap::tm_lines()

all_streets_city_map
```

How many of them are dedicated to women?

```{r}
tmap::tmap_mode(mode = "plot")

city_map <- tmap::tm_shape(city_boundary) + 
  tmap::tm_polygons() +
  tmap::tm_shape(city_roads) +
  tmap::tm_lines(col = "Gender", palette = "Set1", textNA = "other")

city_map
```


Here you can have a closer look with an interactive version of the map: 

```{r}
tmap::tmap_mode(mode = "view")

city_map_interactive <- tmap::tm_shape(city_boundary) + 
  tmap::tm_polygons(col = "lightblue", alpha = 0.2, popup.vars = FALSE) +
  tmap::tm_shape(city_roads) +
  tmap::tm_lines(col = "Gender",
                 lwd = 2,
                 palette = "Set1",
                 textNA = "other",
                 id = "name",
                 popup.vars = c("Gender", "Description"))
city_map_interactive
```

```{r message=FALSE, warning=FALSE}
city_roads %>%
  dplyr::arrange(Gender) %>% 
  sf::st_set_geometry(NULL) %>% 
  dplyr::select(name, Gender, Description) %>% 
  dplyr::distinct(name, .keep_all = TRUE) %>% 
  DT::datatable(rownames = FALSE)
```

